core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    path("schedule_entry/", TemplateView.as_view(template_name="pages/schedule_entry.html"), name="schedule_entry"),
    path("schedule_list/", TemplateView.as_view(template_name="pages/schedule_list.html"), name="schedule_list"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("apps.users.urls", namespace="users")),
    path("schedules/", include("apps.schedule.urls", namespace="schedules")),
    path("accounts/", include("allauth.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("core.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path('api-auth/', include('rest_framework.urls')),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path("api/docs/", SpectacularSwaggerView.as_view(url_name="api-schema"), name="api-docs",),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

apps/schedule/models.py
from django.conf import settings
from django.db import models


class Schedule(models.Model):
    BIWEEKLY_SCHEDULE_CHOICES = [
        ('A', 'Biweekly Schedule A'),
        ('B', 'Biweekly Schedule B'),
    ]
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    biweekly_schedule = models.CharField(
        max_length=1,
        choices=BIWEEKLY_SCHEDULE_CHOICES,
        default='A',
    )

    def __str__(self):
        return f"{self.user} - {self.date}"

apps/templates/pages/about.html
{% extends "base.html" %}

{% block content %}
<h1>Hello</h1>

{% endblock content %}

apps/templates/pages/home.html
{% extends "base.html" %}

apps/templates/pages/schedule_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Schedule Detail</h1>
  <table>
    <tr>
      <th>User:</th>
      <td>{{ object.user }}</td>
    </tr>
    <tr>
      <th>Date:</th>
      <td>{{ object.date }}</td>
    </tr>
    <tr>
      <th>Start Time:</th>
      <td>{{ object.start_time }}</td>
    </tr>
    <tr>
      <th>End Time:</th>
      <td>{{ object.end_time }}</td>
    </tr>
    <tr>
      <th>Biweekly Schedule:</th>
      <td>{{ object.biweekly_schedule }}</td>
    </tr>
  </table>
{% endblock %}

apps/templates/pages/schedule_entry.html
{% extends "base.html" %}

{% block content %}
<div class="container mx-auto">
    <h1 class="mb-4">Employee Schedule Entry</h1>
    <form method="POST">
        {% csrf_token %}
        <div class="row mb-3">
            <label for="employeeName" class="col-sm-2 col-form-label">Employee Name</label>
            <div class="col-sm-10">
                <select class="form-select" aria-label="Employee Name" id="employeeName" name="employee_name">
                    <option selected disabled>Select an employee</option>
                    {% for schedule in schedules %}
                    <option value="{{ schedule.user }}">{{ schedule.user }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="row mb-3">
            <label for="date" class="col-sm-2 col-form-label">Date</label>
            <div class="col-sm-10">
                <input type="date" class="form-control" id="date" name="date">
            </div>
        </div>
        <div class="row mb-3">
            <label for="startTime" class="col-sm-2 col-form-label">Start Time</label>
            <div class="col-sm-10">
                <input type="time" class="form-control" id="startTime" name="start_time">
            </div>
        </div>
        <div class="row mb-3">
            <label for="endTime" class="col-sm-2 col-form-label">End Time</label>
            <div class="col-sm-10">
                <input type="time" class="form-control" id="endTime" name="end_time">
            </div>
        </div>
        <div class="row mb-3">
            <label for="notes" class="col-sm-2 col-form-label">Notes</label>
            <div class="col-sm-10">
                <textarea class="form-control" id="notes" rows="3" name="notes"></textarea>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-sm-10 offset-sm-2">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
</div>

{% endblock content %}

apps/templates/pages/schedule_list.html
{% extends "base.html" %}

{% block content %}

<div class="container mx-auto text-primary">
    <h1 class="mb-4">Schedule List</h1>
    <table class="table text-primary">
        <thead>
            <tr>
                <th>User</th>
                <th>Date</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Biweekly Schedule</th>
            </tr>
        </thead>
        <tbody>
            
            {% for schedule in schedules %}
            <tr>          
                <td>{{ schedule.user }}</td>
                <td>{{ schedule.date }}</td>
                <td>{{ schedule.start_time }}</td>
                <td>{{ schedule.end_time }}</td>
                <td>{{ schedule.get_biweekly_schedule_display }}</td>       
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}